# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plantilla_Grafica.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FiguraCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as BarraNavegacion


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(615, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 51, 21))
        self.label_2.setObjectName("label_2")
        self.txt_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(80, 70, 113, 20))
        self.txt_titulo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.txt_titulo.setObjectName("txt_titulo")
        self.sp_Ymax = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_Ymax.setGeometry(QtCore.QRect(530, 290, 61, 22))
        self.sp_Ymax.setObjectName("sp_Ymin_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 100, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(340, 80, 91, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.cb_ColorLinea = QtWidgets.QComboBox(self.centralwidget)
        self.cb_ColorLinea.setGeometry(QtCore.QRect(490, 70, 111, 22))
        self.cb_ColorLinea.setObjectName("cb_ColorLinea")
        self.btn_graficar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_graficar.setGeometry(QtCore.QRect(220, 40, 71, 31))
        self.btn_graficar.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_graficar.setObjectName("btn_graficar")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(490, 330, 51, 21))
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 210, 51, 21))
        self.label_8.setObjectName("label_8")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(450, 90, 20, 351))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.sp_Xmin = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_Xmin.setGeometry(QtCore.QRect(530, 130, 61, 22))
        self.sp_Xmin.setObjectName("sp_Xmin")
        self.btn_titulo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_titulo.setGeometry(QtCore.QRect(220, 80, 71, 31))
        self.btn_titulo.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_titulo.setObjectName("btn_titulo")
        self.sp_divisionesX = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_divisionesX.setGeometry(QtCore.QRect(550, 210, 41, 22))
        self.sp_divisionesX.setObjectName("sp_divisionesX")
        self.txt_polinomio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_polinomio.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.txt_polinomio.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.txt_polinomio.setText("")
        self.txt_polinomio.setObjectName("txt_polinomio")
        self.sp_Xmax = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_Xmax.setGeometry(QtCore.QRect(530, 170, 61, 22))
        self.sp_Xmax.setObjectName("sp_Xmax")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 51, 21))
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(490, 370, 91, 21))
        self.label_11.setObjectName("label_11")
        self.sp_Ymin = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_Ymin.setGeometry(QtCore.QRect(530, 250, 61, 22))
        self.sp_Ymin.setObjectName("sp_Ymin")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 20, 20, 161))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_limpiar.setGeometry(QtCore.QRect(350, 40, 71, 31))
        self.btn_limpiar.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.sp_divisionesY = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_divisionesY.setGeometry(QtCore.QRect(550, 330, 41, 22))
        self.sp_divisionesY.setObjectName("sp_divisionesY")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 130, 31, 21))
        self.label_6.setObjectName("label_6")
        self.btn_grilla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_grilla.setGeometry(QtCore.QRect(100, 110, 71, 31))
        self.btn_grilla.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_grilla.setObjectName("btn_grilla")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 51, 21))
        self.label_3.setObjectName("label_3")
        self.sp_anchoLinea = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_anchoLinea.setGeometry(QtCore.QRect(490, 400, 101, 22))
        self.sp_anchoLinea.setObjectName("sp_anchoLinea")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(490, 290, 31, 21))
        self.label_9.setObjectName("label_9")
        self.cb_estiloLinea = QtWidgets.QComboBox(self.centralwidget)
        self.cb_estiloLinea.setGeometry(QtCore.QRect(340, 130, 91, 22))
        self.cb_estiloLinea.setObjectName("cb_estiloLinea")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 40, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 190, 411, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 170, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(490, 250, 31, 21))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 615, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.figure = plt.figure(figsize=(15, 5))
        self.canvas = FiguraCanvas(self.figure)

        self.ax = self.figure.add_subplot(111)
        # para referir al mismo axes

        self.toolbar = BarraNavegacion(self.canvas, self)

        self.verticalLayout.addWidget(self.canvas)
        self.verticalLayout.addWidget(self.toolbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Titulo:"))
        self.label_4.setText(_translate("MainWindow", "Estado de linea"))
        self.btn_graficar.setText(_translate("MainWindow", "Graficar"))
        self.label_12.setText(_translate("MainWindow", "T.Divisiones"))
        self.label_8.setText(_translate("MainWindow", "T.Divisiones"))
        self.btn_titulo.setText(_translate("MainWindow", "Establecer"))
        self.label.setText(_translate("MainWindow", "Polinomio:"))
        self.label_11.setText(_translate("MainWindow", "Ancho de la linea"))
        self.btn_limpiar.setText(_translate("MainWindow", "Limpiar grafico"))
        self.label_6.setText(_translate("MainWindow", "Xmin:"))
        self.btn_grilla.setText(_translate("MainWindow", "OFF"))
        self.label_3.setText(_translate("MainWindow", "Grilla:"))
        self.label_9.setText(_translate("MainWindow", "Ymax:"))
        self.label_5.setText(_translate("MainWindow", "Color de la linea:"))
        self.label_7.setText(_translate("MainWindow", "Xmax:"))
        self.label_10.setText(_translate("MainWindow", "Ymin:"))

        self.txt_polinomio.setText(_translate("MainWindow", "2x^2+4x+3"))
